name: Check

on:
  push:
    branches:
      - main
      - master
      - rec
  pull_request:
  workflow_dispatch:

jobs:
  check:
    env:
      node_version: 18
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Set example env
        run: cp .env.example .env
      - name: Lint check
        run: npm run lint
      - name: Format check
        run: npm run prettier
      - name: Unit & Integration tests
        run: npm run test
      - name: Check dependencies usage
        run: npm run depcheck
      - name: Banned Keywords
        run: bash ./scripts/banned-keywords.sh
